// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ticket.proto

package ticket_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OPEN        Status = 0
	Status_IN_PROGRESS Status = 1
	Status_CLOSED      Status = 2
)

var Status_name = map[int32]string{
	0: "OPEN",
	1: "IN_PROGRESS",
	2: "CLOSED",
}

var Status_value = map[string]int32{
	"OPEN":        0,
	"IN_PROGRESS": 1,
	"CLOSED":      2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{0}
}

type Ticket struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=ticket.v1.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ticket) Reset()         { *m = Ticket{} }
func (m *Ticket) String() string { return proto.CompactTextString(m) }
func (*Ticket) ProtoMessage()    {}
func (*Ticket) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{0}
}

func (m *Ticket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ticket.Unmarshal(m, b)
}
func (m *Ticket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ticket.Marshal(b, m, deterministic)
}
func (m *Ticket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ticket.Merge(m, src)
}
func (m *Ticket) XXX_Size() int {
	return xxx_messageInfo_Ticket.Size(m)
}
func (m *Ticket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ticket.DiscardUnknown(m)
}

var xxx_messageInfo_Ticket proto.InternalMessageInfo

func (m *Ticket) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ticket) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Ticket) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OPEN
}

type CreateRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateResponse struct {
	Ticket               *Ticket  `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetTicket() *Ticket {
	if m != nil {
		return m.Ticket
	}
	return nil
}

func init() {
	proto.RegisterEnum("ticket.v1.Status", Status_name, Status_value)
	proto.RegisterType((*Ticket)(nil), "ticket.v1.Ticket")
	proto.RegisterType((*CreateRequest)(nil), "ticket.v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "ticket.v1.CreateResponse")
}

func init() { proto.RegisterFile("ticket.proto", fileDescriptor_98a6c21780e82d22) }

var fileDescriptor_98a6c21780e82d22 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xeb, 0x00, 0x16, 0xbd, 0xd2, 0x10, 0x4e, 0x0c, 0x81, 0x29, 0xca, 0x54, 0x18, 0x82,
	0x28, 0x23, 0x03, 0x43, 0x89, 0x2a, 0x24, 0xd4, 0x44, 0x36, 0x0b, 0x13, 0x2a, 0xc9, 0x0d, 0x16,
	0xa8, 0x09, 0xf1, 0xb5, 0xbf, 0x1f, 0xc9, 0x0e, 0x90, 0x4a, 0x8c, 0xef, 0xee, 0xf4, 0xbd, 0xf7,
	0x0e, 0x4e, 0xd8, 0x54, 0x1f, 0xc4, 0x59, 0xdb, 0x35, 0xdc, 0xe0, 0xb8, 0x57, 0xbb, 0xdb, 0xf4,
	0x15, 0xe4, 0x8b, 0x13, 0x18, 0x42, 0x60, 0xea, 0x58, 0x24, 0x62, 0x36, 0x56, 0x81, 0xa9, 0xf1,
	0x1c, 0x8e, 0xd8, 0xf0, 0x27, 0xc5, 0x81, 0x1b, 0x79, 0x81, 0x57, 0x20, 0x2d, 0xaf, 0x79, 0x6b,
	0xe3, 0x83, 0x44, 0xcc, 0xc2, 0xf9, 0x59, 0xf6, 0xcb, 0xca, 0xb4, 0x5b, 0xa8, 0xfe, 0x20, 0x5d,
	0xc2, 0x74, 0xd1, 0xd1, 0x9a, 0x49, 0xd1, 0xd7, 0x96, 0x2c, 0xff, 0x11, 0xc5, 0x90, 0x98, 0xc0,
	0xa4, 0x26, 0x5b, 0x75, 0xa6, 0x65, 0xd3, 0x6c, 0x7a, 0xb7, 0xe1, 0x28, 0xbd, 0x87, 0xf0, 0x07,
	0x64, 0xdb, 0x66, 0x63, 0x5d, 0x0a, 0x6f, 0xeb, 0x50, 0x93, 0xbd, 0x14, 0xbe, 0x8e, 0xea, 0x0f,
	0xae, 0x6f, 0x40, 0xfa, 0x5c, 0x78, 0x0c, 0x87, 0x45, 0x99, 0xaf, 0xa2, 0x11, 0x9e, 0xc2, 0xe4,
	0x69, 0xf5, 0x56, 0xaa, 0x62, 0xa9, 0x72, 0xad, 0x23, 0x81, 0x00, 0x72, 0xf1, 0x5c, 0xe8, 0xfc,
	0x31, 0x0a, 0xe6, 0x25, 0x4c, 0x3d, 0x42, 0x53, 0xb7, 0x33, 0x15, 0xe1, 0x03, 0x48, 0x6f, 0x8f,
	0xf1, 0xc0, 0x66, 0xaf, 0xda, 0xe5, 0xc5, 0x3f, 0x1b, 0x9f, 0x35, 0x1d, 0xbd, 0x4b, 0xf7, 0xf5,
	0xbb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67, 0x1d, 0x0a, 0xe1, 0x85, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TicketServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type ticketServiceClient struct {
	cc *grpc.ClientConn
}

func NewTicketServiceClient(cc *grpc.ClientConn) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/ticket.v1.TicketService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
type TicketServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterTicketServiceServer(s *grpc.Server, srv TicketServiceServer) {
	s.RegisterService(&_TicketService_serviceDesc, srv)
}

func _TicketService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ticket.v1.TicketService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TicketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ticket.v1.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TicketService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ticket.proto",
}
